"""user & suspiciousip

Revision ID: 7ef2a7da1a70
Revises: 1bd1df68897e
Create Date: 2024-01-19 12:06:47.404217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef2a7da1a70'
down_revision: Union[str, None] = '1bd1df68897e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
