"""user & suspiciousip

Revision ID: df92a52b95ce
Revises: 7ef2a7da1a70
Create Date: 2024-01-19 15:09:34.461274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df92a52b95ce'
down_revision: Union[str, None] = '7ef2a7da1a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
